FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat tzdata

COPY package.json package-lock.json* ./

RUN npm install

COPY . .

ENV NEXT_TELEMETRY_DISABLED=1

EXPOSE 3000

CMD ["npm", "run", "dev"]
